# Generated by Django 4.2.5 on 2023-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP code')),
                ('status', models.CharField(choices=[('pend', 'In progress'), ('ok', 'Sent to recipient'), ('err', 'Error')], default='pend', max_length=4, verbose_name='Code send status')),
            ],
        ),
    ]
